version: '3'

services:
  api:
    build: ./api
    image: $DOCKER_IMAGE_API
    container_name: api
    restart: always
    environment:
      TUNNEL_HOST: "host.docker.internal"
      TUNNEL_PORT: "3000"
    networks:
      - more-tech

  nginx:
    build: ./nginx
    image: $DOCKER_IMAGE_NGINX
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - api
    networks:
      - more-tech

networks:
  more-tech:
    driver: bridge